### ISSUE TITLE
Android Auto not working on OP7Pro

### ISSUE THREAD

**Issue by Jorn1993** [GeorgeDachamp/dot_device_oneplus_guacamole#1]
Hi,

Android Auto is not working with my OP7Pro. Had no problems with other phones or other ROMs. All access rights were approved.

Nothing happens when plugged into the car. The car doesn't see my phone.

**Comment by GeorgeDachamp** [comment]
Update gulch kernel to latest

**Comment by Jorn1993** [comment]
How? And Why? Isn't this included in the ROM?

**Comment by GeorgeDachamp** [comment]
Use telegram support channel. And it's because I haven't had a need to
update official rom yet.

**Comment by Jorn1993** [comment]
I asked in the DotOs community but no one seems to help. I downloaded the latest GulchR kernel zip, but can't flash it using ADB Sideload. What should I do?

**Comment by GeorgeDachamp** [comment]
https://t.me/dotos_hotdogb

**Comment by Jorn1993** [comment]
I managed to get it to work ! Thanks !!
